language: clojure
lein: lein2
env: DATABASE_NAME="sync_data_json_test" DATABASE_USER="postgres" DATABASE_PASSWORD="" DATABASE_HOST="localhost"
before_script:
  - psql -c 'create database sync_data_json_test;' -U postgres
  - lein ragtime migrate -d "jdbc:postgresql://localhost:5432/sync_data_json_test?user=postgres"
script: lein2 midje
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  allow_failures:
    - oraclejdk7
    - oraclejdk8
